package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/kenkyu392/go-tm/internal/tag"
	_ "github.com/kenkyu392/go-tm/internal/tag/all"
)

const (
	dirName  = ""
	fileName = "tags.gen.go"
)

const tmpl = `// Code generated by go-tm. DO NOT EDIT.
package tm
import ("golang.org/x/text/language")
// The following %d languages are defined.
var (
	%s
)
`
const codeDefinitionBlockTmpl = `// %s
TagDisplayName_%s = "%s"
TagLanguageDisplayName_%s = "%s"
TagRegionDisplayName_%s = "%s"
TagOriginalName_%s = "%s"
Tag_%s = language.MustParse(TagOriginalName_%s)
TagName_%s = Tag_%s.String() // The tag name may have changed from the original name after parsing.
Language_%s = Language{
	DisplayName: TagDisplayName_%s,
	LanguageDisplayName: TagLanguageDisplayName_%s,
	RegionDisplayName: TagRegionDisplayName_%s,
	OriginalName: TagOriginalName_%s,
	Tag: Tag_%s,
	TagName: TagName_%s,
}`

func outPath(dir, file string) (string, error) {
	outDir, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}

	stat, err := os.Stat(outDir)
	if err != nil {
		return "", err
	}

	if !stat.IsDir() {
		return "", fmt.Errorf("%s is not a directory", outDir)
	}
	outDir = outDir + "/"
	return filepath.Join(outDir, file), nil
}

func genCode() string {
	regRegionName := regexp.MustCompile(`\((.*)\)$`)
	list := make([]string, 0)
	for _, v := range tag.Languages() {
		t := v.TagName
		vt := strings.ReplaceAll(t, "-", "")
		regionNameBlock := regRegionName.FindString(v.DisplayName)
		languageDisplayName := strings.TrimSpace(strings.TrimSuffix(v.DisplayName, regionNameBlock))
		regionDisplayName := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(regionNameBlock, "("), ")"))
		list = append(list, fmt.Sprintf(codeDefinitionBlockTmpl,
			v.DisplayName,
			vt, v.DisplayName,
			vt, languageDisplayName,
			vt, regionDisplayName,
			vt, t,
			vt, vt,
			vt, vt,
			vt, vt, vt, vt, vt, vt, vt,
		))
	}
	// sort.Strings(list)
	return fmt.Sprintf(tmpl, len(list), strings.TrimSpace(strings.Join(list, "\n\t")))
}

func main() {
	out, err := outPath(dirName, fileName)
	if err != nil {
		panic("generate: " + err.Error())
	}
	code := genCode()
	if err := ioutil.WriteFile(out, []byte(code), os.ModePerm); err != nil {
		panic("generate: " + err.Error())
	}
	print("generated: ", out)
}
