package french

import (
	"github.com/kenkyu392/go-tm/tag"
)

/*
fr-BE,French (Belgium)
fr-BF,French (Burkina Faso)
fr-BI,French (Burundi)
fr-BJ,French (Benin)
fr-BL,French (Saint Barthélemy)
fr-CA,French (Canada)
fr-CD,French (Democratic Republic of the Congo)
fr-CF,French (Central African Republic)
fr-CG,French (Republic of the Congo)
fr-CH,French (Switzerland)
fr-CI,French (Côte d'Ivoire)
fr-CM,French (Cameroon)
fr-DJ,French (Djibouti)
fr-DZ,French (Algeria)
fr-FR,French (France)
fr-GA,French (Gabon)
fr-GF,French (French Guiana)
fr-GN,French (Guinea)
fr-GP,French (Guadeloupe)
fr-GQ,French (Equatorial Guinea)
fr-HT,French (Haiti)
fr-KM,French (Comoros)
fr-LU,French (Luxembourg)
fr-MA,French (Morocco)
fr-MC,French (Principality of Monaco)
fr-MF,French (Saint Martin)
fr-MG,French (Madagascar)
fr-ML,French (Mali)
fr-MQ,French (Martinique)
fr-MR,French (Mauritania)
fr-MU,French (Mauritius)
fr-NC,French (New Caledonia)
fr-NE,French (Niger)
fr-PF,French (French Polynesia)
fr-PM,French (Saint Pierre and Miquelon)
fr-RE,French (Reunion)
fr-RW,French (Rwanda)
fr-SC,French (Seychelles)
fr-SN,French (Senegal)
fr-SY,French (Syria)
fr-TD,French (Chad)
fr-TG,French (Togo)
fr-TN,French (Tunisia)
fr-VU,French (Vanuatu)
fr-WF,French (Wallis and Futuna)
fr-YT,French (Mayotte)
*/

func init() {
	tag.Register("fr-BE", "French (Belgium)")
	tag.Register("fr-BF", "French (Burkina Faso)")
	tag.Register("fr-BI", "French (Burundi)")
	tag.Register("fr-BJ", "French (Benin)")
	tag.Register("fr-BL", "French (Saint Barthélemy)")
	tag.Register("fr-CA", "French (Canada)")
	tag.Register("fr-CD", "French (Democratic Republic of the Congo)")
	tag.Register("fr-CF", "French (Central African Republic)")
	tag.Register("fr-CG", "French (Republic of the Congo)")
	tag.Register("fr-CH", "French (Switzerland)")
	tag.Register("fr-CI", "French (Côte d'Ivoire)")
	tag.Register("fr-CM", "French (Cameroon)")
	tag.Register("fr-DJ", "French (Djibouti)")
	tag.Register("fr-DZ", "French (Algeria)")
	tag.Register("fr-FR", "French (France)")
	tag.Register("fr-GA", "French (Gabon)")
	tag.Register("fr-GF", "French (French Guiana)")
	tag.Register("fr-GN", "French (Guinea)")
	tag.Register("fr-GP", "French (Guadeloupe)")
	tag.Register("fr-GQ", "French (Equatorial Guinea)")
	tag.Register("fr-HT", "French (Haiti)")
	tag.Register("fr-KM", "French (Comoros)")
	tag.Register("fr-LU", "French (Luxembourg)")
	tag.Register("fr-MA", "French (Morocco)")
	tag.Register("fr-MC", "French (Principality of Monaco)")
	tag.Register("fr-MF", "French (Saint Martin)")
	tag.Register("fr-MG", "French (Madagascar)")
	tag.Register("fr-ML", "French (Mali)")
	tag.Register("fr-MQ", "French (Martinique)")
	tag.Register("fr-MR", "French (Mauritania)")
	tag.Register("fr-MU", "French (Mauritius)")
	tag.Register("fr-NC", "French (New Caledonia)")
	tag.Register("fr-NE", "French (Niger)")
	tag.Register("fr-PF", "French (French Polynesia)")
	tag.Register("fr-PM", "French (Saint Pierre and Miquelon)")
	tag.Register("fr-RE", "French (Reunion)")
	tag.Register("fr-RW", "French (Rwanda)")
	tag.Register("fr-SC", "French (Seychelles)")
	tag.Register("fr-SN", "French (Senegal)")
	tag.Register("fr-SY", "French (Syria)")
	tag.Register("fr-TD", "French (Chad)")
	tag.Register("fr-TG", "French (Togo)")
	tag.Register("fr-TN", "French (Tunisia)")
	tag.Register("fr-VU", "French (Vanuatu)")
	tag.Register("fr-WF", "French (Wallis and Futuna)")
	tag.Register("fr-YT", "French (Mayotte)")
}
